[package]
name = "dbus-now-playing"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
zbus = { version = "4.4", features = ["blocking"] }
