# To connect to a specific player, uncomment and set the service name below.
# Example for Spotify: dbus_service = "org.mpris.MediaPlayer2.spotify"
# dbus_service = "org.mpris.MediaPlayer2.Supersonic"

fg_color = "#FFFFFF"
bg_color = "#000000"
window_x = 0
window_y = 1420
