dbus_service = "org.mpris.MediaPlayer2.Supersonic"
dbus_path = "/org/mpris/MediaPlayer2"
dbus_interface = "org.mpris.MediaPlayer2.Player"
fg_color = "#FFFFFF"
bg_color = "#000000"
window_x = 0
window_y = 1390
